#!/bin/sh

try()
{
	cnt=0
	cnt_max=5
	echo $@
	while true;
	do
		cnt=`expr $cnt + 1`
		echo "==> try $cnt/$cnt_max"
		$@
		[ $? -eq 0 ] && return 0
		if [ $cnt -ge $cnt_max ];then
			return 1
		fi
		sleep 1
	done
}

try $@
